-define(SET, riak_dt_orswot).
-define(APP, partisan).
-define(PEER_IP, {127,0,0,1}).
-define(PEER_PORT, 9000).
-define(PEER_SERVICE_SERVER, partisan_peer_service_server).
-define(FANOUT, 5).
-define(PEER_SERVICE_MANAGER, partisan_default_peer_service_manager).
-define(GOSSIP_INTERVAL, 10000).

-type actor() :: binary().
-type connections() :: dict:dict(node(), port()).
-type node_spec() :: {node(), inet:ip_address(), non_neg_integer()}.
-type message() :: term().
-type name() :: node().
